name: Spellcheck Action

on:
  pull_request:
  push:
    branches:
      - humble

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.33.1
      name: Spellcheck